use LostFound;

CREATE TABLE tbCtt(
	cttCod	INT NOT NULL IDENTITY(1,1),
	cttTipCod	INT NOT NULL,
	pesCod	INT NOT NULL,
	cttDsc	VARCHAR(50) NOT NULL,
		CONSTRAINT PK_tbCtt_cttCod PRIMARY KEY (cttCod)
);

CREATE TABLE tbCttTip(
	cttTipCod	INT NOT NULL IDENTITY(1,1),
	cttTipDsc	VARCHAR(30) NOT NULL,
		CONSTRAINT PK_tbCttTip PRIMARY KEY (cttTipCod)
);

ALTER TABLE tbCtt ADD CONSTRAINT FK_tbCtt_tbCttTip_cttTipCod FOREIGN KEY (cttTipCod) REFERENCES tbCttTip(cttTipCod);
ALTER TABLE tbCtt ADD CONSTRAINT FK_tbCtt_tbPes_pesCod FOREIGN KEY (pesCod) REFERENCES tbPes(pesCod);
